const LOG_IN = 'LOG_IN';
const LOG_OUT = 'LOG_OUT';
const UPDATE_USER = 'UPDATE_USER';
const CREATE_USER = 'CREATE_USER';
const GOT_COHORTS = 'GOT_COHORTS';
const GOT_ONE_COHORT = 'GOT_ONE_COHORT';
const UPDATE_CURRENT_COHORT = 'UPDATE_CURRENT_COHORT';
const GOT_ONE_STUDENT = 'GOT_ONE_STUDENT';
const GOT_CURRENT_COHORT_STUDENTS = 'GOT_CURRENT_COHORT_STUDENTS';
const ADD_ONE_STUDENT = 'ADD_ONE_STUDENT';

export {
  LOG_IN,
  LOG_OUT,
  UPDATE_USER,
  CREATE_USER,
  UPDATE_CURRENT_COHORT,
  GOT_COHORTS,
  GOT_ONE_COHORT,
  GOT_ONE_STUDENT,
  GOT_CURRENT_COHORT_STUDENTS,
  ADD_ONE_STUDENT,
};
