const LOG_IN = "LOG_IN";
const LOG_OUT = "LOG_OUT";
const UPDATE_USER = "UPDATE_USER";
const GOT_COHORTS = "GOT_COHORTS";
const GOT_ONE_COHORT = "GOT_ONE_COHORT";
const UPDATE_CURRENT_COHORT = "UPDATE_CURRENT_COHORT";
const GOT_ONE_STUDENT = "GOT_ONE_STUDENT";

export {
  LOG_IN, LOG_OUT, UPDATE_USER, UPDATE_CURRENT_COHORT, GOT_COHORTS, GOT_ONE_COHORT, GOT_ONE_STUDENT
}